[package]
name = "cardano-c"
version = "0.1.0"
authors = ["Nicolas Di Prima <nicolas.diprima@iohk.io>", "Vincent Hanquez <vincent.hanquez@iohk.io>"]

[lib]
crate-type = ["staticlib" ]

[dependencies]
cardano = { path = "../cardano" }
